/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javalab8;

import java.awt.Color;
import javalab8.interfaces.IMovable;

/**
 *
 * @author borisost
 */
public class Frame extends javax.swing.JFrame {

    private IMovable viewpoint;
    
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        setBackground(Color.BLACK);
    }

    public void setViewpoint(IMovable viewpoint) {
        this.viewpoint = viewpoint;
        pane.setViewpoint(viewpoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javalab8.Pane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pane.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(pane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == 37){
            viewpoint.move(-1, 0);
        }
        else if(evt.getKeyCode() == 39){
            viewpoint.move(1, 0);
        }
    }//GEN-LAST:event_formKeyPressed

    public Pane getPane(){
        return pane;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javalab8.Pane pane;
    // End of variables declaration//GEN-END:variables
}
