/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javalab8;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import javalab8.interfaces.IMovable;
import javalab8.interfaces.IPaintable;

/**
 *
 * @author borisost
 */
public class Pane extends javax.swing.JPanel {

    List<IPaintable> objects;
    IMovable viewpoint;
    
    public Pane() {
        initComponents();
        objects = new ArrayList<>();
    }

    public void addPaintableObj(IPaintable obj){
        objects.add(obj);
    }
    
    public void removePaintableObj(IPaintable obj){
        objects.remove(obj);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        if(viewpoint != null){
            g.translate(viewpoint.getX(), viewpoint.getY());
        }
        for(IPaintable obj : objects){
            obj.draw(g);
        }
    }
    
    public void setViewpoint(IMovable viewpoint) {
        this.viewpoint = viewpoint;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
